# Generated by Django 4.2.11 on 2024-06-24 07:38

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название категории')),
                ('seo', models.CharField(blank=True, null=True)),
                ('url', models.CharField(blank=True, null=True)),
                ('shard', models.CharField(blank=True, null=True)),
                ('query', models.CharField(blank=True, null=True)),
                ('childs', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=True)),
                ('sub_category', models.JSONField(blank=True, default=None, null=True, verbose_name='подкатегория')),
                ('filter_category', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='goods.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
            },
        ),
    ]
