# Generated by Django 4.2.11 on 2024-06-29 14:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_id', models.IntegerField()),
                ('name', models.CharField(verbose_name='Название категории')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Брэнд',
                'verbose_name_plural': 'Брэнды',
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название категории')),
                ('price', models.IntegerField(default=0, verbose_name='цена')),
                ('quantity', models.IntegerField(default=0, verbose_name='количество')),
                ('root', models.IntegerField(default=None, verbose_name='Рейтинг')),
                ('subjectId', models.IntegerField(default=None, verbose_name='Под категория')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('pics', models.JSONField(verbose_name='Картинки')),
                ('price_history', models.JSONField(verbose_name='история цены')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('discount', models.IntegerField(default=0, verbose_name='скидка')),
                ('brand', models.ForeignKey(blank=True, db_column='brand', null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.brand', verbose_name='Брэнд')),
                ('category', mptt.fields.TreeForeignKey(db_column='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
            },
        ),
    ]
