# Generated by Django 4.2.11 on 2024-07-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_brand_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ["-updated"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
