# Generated by Django 4.2.11 on 2024-08-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.SmallIntegerField(choices=[(0, 'Картой'), (1, 'СБП'), (2, 'Наличными')], default=0),
        ),
    ]
