# Generated by Django 4.2.11 on 2024-08-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.SmallIntegerField(choices=[(0, 'Картой'), (1, 'СБП'), (2, 'Наличными')], default=0, verbose_name='Способ оплаты'),
        ),
    ]
