# Generated by Django 4.2.11 on 2024-08-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orders_sum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='сумма'),
        ),
    ]
